name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=23.3.2
  - mlflow=2.9.2
  - hydra-core=1.3.2
  - pip:
      - wandb==0.16.1
      - hydra-joblib-launcher==1.2.0
