name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.4
  - pip=23.3.2
  - scikit-learn=1.3.2
  - matplotlib==3.8.2
  - plotly==5.18.0
  - pillow=10.1.0
  - mlflow=2.9.2
  - pip:
      - wandb==0.16.1
